"""update table

Revision ID: 05ce7c3631e2
Revises: 1891bee64e51
Create Date: 2024-08-17 21:11:51.436525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05ce7c3631e2'
down_revision: Union[str, None] = '1891bee64e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupquestion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questiontoiec', sa.Column('group_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'questiontoiec', 'groupquestion', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questiontoiec', type_='foreignkey')
    op.drop_column('questiontoiec', 'group_id')
    op.drop_table('groupquestion')
    # ### end Alembic commands ###
