"""update code

Revision ID: 0ee27e16f5ff
Revises: 117e21a6157c
Create Date: 2024-08-21 10:45:43.931036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ee27e16f5ff'
down_revision: Union[str, None] = '117e21a6157c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupquestion', sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('groupquestion', sa.Column('question_audio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('groupquestion', 'question')
    op.drop_column('questiontoiec', 'direction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questiontoiec', sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('groupquestion', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('groupquestion', 'question_audio')
    op.drop_column('groupquestion', 'question_text')
    # ### end Alembic commands ###
