"""update code

Revision ID: 117e21a6157c
Revises: a006e54eaa35
Create Date: 2024-08-21 10:20:54.138637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '117e21a6157c'
down_revision: Union[str, None] = 'a006e54eaa35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupquestion', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('groupquestion', 'title')
    op.add_column('parttoiec', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('questiontoiec', sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('questiontoiec', sa.Column('question_audio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('questiontoiec', sa.Column('answer_choices', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('questiontoiec', sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('questiontoiec', 'list_answer')
    op.drop_column('questiontoiec', 'question')
    op.drop_column('questiontoiec', 'audio')
    op.add_column('toiec', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('toiec', sa.Column('total_part', sa.Integer(), nullable=False))
    op.add_column('toiec', sa.Column('total_questions', sa.Integer(), nullable=False))
    op.add_column('toiec', sa.Column('total_time', sa.Integer(), nullable=False))
    op.drop_column('toiec', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toiec', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('toiec', 'total_time')
    op.drop_column('toiec', 'total_questions')
    op.drop_column('toiec', 'total_part')
    op.drop_column('toiec', 'name')
    op.add_column('questiontoiec', sa.Column('audio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questiontoiec', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questiontoiec', sa.Column('list_answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('questiontoiec', 'correct_answer')
    op.drop_column('questiontoiec', 'answer_choices')
    op.drop_column('questiontoiec', 'question_audio')
    op.drop_column('questiontoiec', 'question_text')
    op.drop_column('parttoiec', 'name')
    op.add_column('groupquestion', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('groupquestion', 'name')
    # ### end Alembic commands ###
