"""update table

Revision ID: 50bb4cf3fea7
Revises: 05ce7c3631e2
Create Date: 2024-08-17 21:22:15.223322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50bb4cf3fea7'
down_revision: Union[str, None] = '05ce7c3631e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupquestion', sa.Column('toiec_id', sa.Uuid(), nullable=False))
    op.add_column('groupquestion', sa.Column('part_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'groupquestion', 'toiec', ['toiec_id'], ['id'])
    op.create_foreign_key(None, 'groupquestion', 'parttoiec', ['part_id'], ['id'])
    op.add_column('questiontoiec', sa.Column('part_id', sa.Uuid(), nullable=False))
    op.drop_constraint('questiontoiec_toiec_id_fkey', 'questiontoiec', type_='foreignkey')
    op.create_foreign_key(None, 'questiontoiec', 'parttoiec', ['part_id'], ['id'])
    op.create_foreign_key(None, 'questiontoiec', 'toiec', ['toiec_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questiontoiec', type_='foreignkey')
    op.drop_constraint(None, 'questiontoiec', type_='foreignkey')
    op.create_foreign_key('questiontoiec_toiec_id_fkey', 'questiontoiec', 'parttoiec', ['toiec_id'], ['id'])
    op.drop_column('questiontoiec', 'part_id')
    op.drop_constraint(None, 'groupquestion', type_='foreignkey')
    op.drop_constraint(None, 'groupquestion', type_='foreignkey')
    op.drop_column('groupquestion', 'part_id')
    op.drop_column('groupquestion', 'toiec_id')
    # ### end Alembic commands ###
