"""update table

Revision ID: a006e54eaa35
Revises: 5394adb91c0f
Create Date: 2024-08-19 20:23:04.539179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a006e54eaa35'
down_revision: Union[str, None] = '5394adb91c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configtoiec', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('configtoiec', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configtoiec', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('configtoiec', 'name')
    # ### end Alembic commands ###
